version: '1.1'

networks:
  dev:
    driver: bridge

services:
  banking-postgres:
    container_name: banking-postgres-container
    image: postgres:15.5
    ports:
      - "6477:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: BankingDb
    networks:
      - dev
    restart: unless-stopped

  banking-pgadmin:
    container_name: banking-pgadmin-container
    image: dpage/pgadmin4:8.1
    depends_on:
      - banking-postgres
    ports:
      - "6060:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - dev
    restart: unless-stopped
  
  banking-apiservice:
    container_name: banking-apiservice
    image: veyseldilim/banking-apiservice:1.1
    depends_on:
      - banking-postgres
    ports:
      - "5154:5154"
    environment:
      ASPNETCORE_ENVIRONMENT : "DevContainer"
      ASPNETCORE_URLS : "http://+:5154"
      SecretKey : "MyVerySecretActualKeyAndNothingMoreNothingLess"
    networks:
      - dev
    restart: unless-stopped